"""
Generate 5,640+ canonical questions across 47 technologies.
"""
import hashlib
import json
import os

def slugify(text: str) -> str:
    cleaned = text.lower().replace("+", "-plus").replace(".", "-").replace("/", "-")
    chars = [c if c.isalnum() or c == "-" else "-" for c in cleaned]
    slug = "".join(chars)
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-")

def generate_qid(q_text: str) -> str:
    cleaned = q_text.strip().lower()
    return hashlib.sha256(cleaned.encode("utf-8")).hexdigest()[:16]

# 47 Technologies and default roles
TECHNOLOGIES_CONFIG = [
    # Languages (7)
    ("Python", "Python Backend / Data Engineer", [
        ("Basics", [
            ("Memory Management", "How does Python manage memory under the hood using reference counting and the cyclic garbage collector?", "Hard", "Technical", "Python uses reference counting as its primary memory management mechanism. When an object's reference count drops to zero, its memory is deallocated immediately. To handle reference cycles (where two or more objects reference each other), Python incorporates a cyclic garbage collector that periodically inspects container objects using three generation heuristics (Gen 0, 1, 2)."),
            ("Mutable vs Immutable", "What is the fundamental difference between mutable and immutable types in Python, and how does it affect variable assignment and function parameter passing?", "Easy", "Conceptual", "Immutable objects (integers, strings, tuples, frozensets) cannot be modified after creation; any modification produces a new object in memory. Mutable objects (lists, dicts, sets) can be modified in place. In Python, arguments are passed by assignment (call-by-object-reference), meaning mutating a mutable parameter inside a function alters the caller's object."),
            ("LEGB Scope Rule", "Explain how Python resolves variable names using the LEGB (Local, Enclosing, Global, Built-in) rule.", "Medium", "Conceptual", "When a variable name is referenced, Python searches scopes sequentially: first the Local scope of the current function, then any Enclosing functions (for closures), then the Global module-level scope, and finally the Built-in namespace containing Python's standard functions. If the variable is not found in any of these four, a NameError is raised."),
            ("Default Argument Pitfall", "Why is using a mutable object like a list or dictionary as a default argument in a Python function dangerous, and what is the standard idiom to prevent it?", "Medium", "Technical", "Default arguments in Python are evaluated once when the function definition is executed, not each time the function is called. If a mutable default argument is modified, that change persists across all subsequent function calls. The standard idiom is to set the default argument to None and initialize a new mutable object inside the function body if the argument is None."),
            ("Identity vs Equality", "What is the difference between the 'is' operator and the '==' operator in Python?", "Easy", "Conceptual", "'is' checks for object identity (whether two variables point to the exact same memory address, verified via id(x)), whereas '==' checks for value equality (invoking the __eq__ method to evaluate if two objects contain equivalent data)."),
            ("__name__ == '__main__'", "What is the purpose of the 'if __name__ == \"__main__\":' construct in Python scripts?", "Easy", "Conceptual", "This construct checks whether the script is being executed directly from the terminal or imported as a module in another script. When executed directly, Python sets the special __name__ variable to '__main__'. When imported, __name__ is set to the module's file name, preventing execution of top-level procedural code."),
            ("Integer Caching & Interning", "How does Python optimize memory for small integers and strings through caching and interning?", "Medium", "Technical", "CPython pre-allocates and caches an array of small integer objects in the range of -5 to 256 at startup. Any reference to integers in this range reuses the cached object rather than allocating a new one. Similarly, string interning ensures that string literals that look like identifiers share the same memory instance, speeding up dictionary key lookups through pointer comparisons."),
            ("sys.getrefcount", "How does the sys.getrefcount() function work, and why does it always report a reference count one higher than expected?", "Medium", "Technical", "sys.getrefcount(obj) returns the current reference count of the specified object. It always reports one higher than expected because passing the object as an argument to sys.getrefcount creates a temporary reference inside the function's stack frame during execution."),
            ("Type Hinting (PEP 484)", "What are the runtime implications of Python type hinting (PEP 484), and how do static analysis tools like Mypy leverage them?", "Medium", "Technical", "Type annotations in Python are completely ignored by the CPython runtime at execution time; they do not enforce types or cause runtime exceptions. Instead, they provide structured metadata stored in __annotations__ that external static analysis tools (like Mypy or Pyright) and IDEs inspect ahead of time to detect type mismatches and prevent bugs."),
            ("Shallow vs Deep Copy", "Explain the difference between a shallow copy and a deep copy in Python, referencing the copy module.", "Easy", "Conceptual", "A shallow copy (copy.copy) constructs a new compound object and inserts references into it to the objects found in the original. A deep copy (copy.deepcopy) constructs a new compound object and recursively inserts copies of the objects found in the original, ensuring changes to nested objects do not affect the source."),
            ("Docstrings vs Comments", "How do Python docstrings differ from standard comments, and how can they be accessed programmatically?", "Easy", "Conceptual", "Comments (prefixed with #) are stripped out during bytecode compilation and are not accessible at runtime. Docstrings (triple-quoted strings placed immediately below a module, class, or function definition) are compiled into bytecode and attached to the object's __doc__ attribute, allowing runtime inspection via help() or obj.__doc__."),
            ("Bytecode Inspection with dis", "How can you use Python's built-in 'dis' module to analyze CPython bytecode, and what insights does it provide?", "Hard", "Technical", "The 'dis' module disassembles Python code objects into human-readable CPython bytecode instructions (such as LOAD_FAST, BINARY_OP, and STORE_FAST). This enables developers to analyze execution flow, verify optimization hypotheses, investigate overhead of abstraction layers, and understand bytecode dispatch mechanics."),
        ]),
        ("Functions", [
            ("*args and **kwargs", "Explain how *args and **kwargs operate in Python function definitions and calls.", "Easy", "Conceptual", "*args packs arbitrary positional arguments into a tuple, while **kwargs packs arbitrary keyword arguments into a dictionary. In function calls, the unpack operator (*) expands an iterable into positional arguments and (**) expands a dictionary into keyword arguments."),
            ("First-Class Functions", "What does it mean for functions to be 'first-class citizens' in Python?", "Easy", "Conceptual", "In Python, functions are first-class objects: they can be assigned to variables, stored in data structures (lists, dicts), passed as arguments to other functions, and returned from other functions as values."),
            ("Closures & Free Variables", "How does a Python closure work, and how does the 'nonlocal' keyword enable state mutation across nested scopes?", "Medium", "Technical", "A closure occurs when a nested function retains access to variables defined in its enclosing scope (free variables stored in __closure__), even after the enclosing function has finished executing. The 'nonlocal' keyword explicitly declares that a variable refers to the nearest enclosing non-global scope, allowing the inner function to rebind and mutate it."),
            ("Lambda Expressions", "What are the syntactic and design limitations of lambda expressions in Python?", "Easy", "Conceptual", "Python lambda expressions are restricted to a single expression whose evaluated result is automatically returned. They cannot contain statements (such as if/elif blocks, loops, pass, or raise), cannot have type annotations, and are intended for short, throwaway utility functions passed to functions like sorted(), map(), or filter()."),
            ("Recursion Limits", "Why does Python have a maximum recursion limit, and how can it be inspected or modified using the sys module?", "Medium", "Technical", "CPython does not perform tail-call optimization (TCO). To prevent C stack overflow crashes, Python imposes a default recursion limit (typically 1000 frames). This can be checked using sys.getrecursionlimit() and modified using sys.setrecursionlimit(), though setting it too high risks segmentation faults."),
            ("functools.partial", "Explain the utility of functools.partial in function composition and currying.", "Medium", "Technical", "functools.partial returns a new callable object that freezes a portion of a function's positional and keyword arguments. When invoked, it combines the frozen arguments with any newly provided arguments, simplifying callbacks and event handlers without requiring verbose wrapper functions."),
            ("Keyword-Only Arguments", "How do you define keyword-only and positional-only arguments in Python 3?", "Medium", "Technical", "Positional-only parameters are placed before a forward slash (/), meaning callers cannot provide them using keyword syntax. Keyword-only parameters are placed after an asterisk (*) or a *args parameter, requiring callers to explicitly specify their names when invoking the function."),
            ("Function Introspection", "How can Python's inspect module be used to inspect function signatures and parameters dynamically?", "Hard", "Technical", "The inspect module's inspect.signature() function extracts structured metadata from callables, providing Parameter objects detailing names, default values, annotations, and kinds (positional-only, keyword-only, var-positional, var-keyword), commonly used by dependency injection and validation frameworks."),
            ("Generator Return Values", "What happens when a Python generator function uses both 'yield' and a 'return' statement with a value?", "Medium", "Technical", "When a generator function executes a return statement with a value, it terminates iteration and raises a StopIteration exception where the return value is stored in the exception's 'value' attribute. When iterated with 'yield from', the returned value becomes the evaluated result of the yield from expression."),
            ("Higher-Order Functions", "Describe the behavior and modern best practices regarding map(), filter(), and reduce() versus list comprehensions.", "Easy", "Conceptual", "map() transforms elements and filter() selects elements lazily using iterators. reduce() from functools aggregates an iterable to a single value. In modern Python, list and generator comprehensions are generally preferred over map() and filter() for readability and performance, while explicit for-loops are preferred over complex reduce() chains."),
            ("Memoization with lru_cache", "How does functools.lru_cache optimize recursive or expensive pure functions?", "Medium", "Technical", "functools.lru_cache wraps a function with a least-recently-used cache implemented via a Python dictionary and a doubly linked list. Function arguments are hashed and used as cache keys. If called with identical arguments, the cached result is returned in O(1) time without re-evaluating the function body."),
            ("Function Metadata Preservation", "Why should functools.wraps always be used when writing higher-order wrapper functions or decorators?", "Medium", "Technical", "When a decorator wraps a function, the wrapper function assumes its own __name__, __doc__, and __module__. functools.wraps copies these attributes from the original decorated function onto the wrapper, preserving introspection, docstrings, and debugging stack traces."),
        ]),
        ("OOP", [
            ("MRO & C3 Linearization", "How does Python resolve method resolution order (MRO) in multiple inheritance using the C3 linearization algorithm?", "Hard", "Technical", "Python calculates method resolution order using the C3 linearization algorithm, accessible via Class.mro(). It preserves local precedence order (classes listed first in inheritance take precedence) and monotonicity (if class A precedes class B in a parent's MRO, it must precede B in all descendant MROs), preventing inheritance inconsistencies."),
            ("@property and Descriptors", "Explain how Python descriptors work and how the @property decorator leverages the descriptor protocol.", "Hard", "Technical", "A descriptor is any object that defines at least one of __get__, __set__, or __delete__. When an attribute on an instance is accessed, Python's attribute lookup checks if the attribute on the class is a descriptor. The @property decorator implements this protocol to dynamically compute return values on attribute access and validate values during assignment."),
            ("__slots__ Optimization", "What is the memory and performance benefit of declaring __slots__ in a Python class?", "Medium", "Technical", "By default, Python instances store attributes in an internal dictionary (__dict__), which has high memory overhead to accommodate dynamic attribute addition. Defining __slots__ allocates a fixed-size array of attribute pointers instead of a __dict__, drastically reducing memory consumption for millions of instances and slightly accelerating attribute access."),
            ("__str__ vs __repr__", "What is the design distinction between __str__ and __repr__ in Python classes?", "Easy", "Conceptual", "__repr__ is intended for developers and debugging, providing an unambiguous string representation that ideally looks like valid Python code to recreate the object. __str__ is intended for end users, providing a clean, readable representation. If __str__ is not defined, Python falls back to __repr__."),
            ("Name Mangling", "How does Python handle private attributes using double-underscore name mangling?", "Easy", "Conceptual", "Attributes prefixed with two leading underscores (e.g. __attr) and at most one trailing underscore are automatically rewritten by the CPython compiler into _ClassName__attr. This prevents accidental attribute shadowing and name collisions in subclasses, though it is not a strict security mechanism since it can still be accessed directly."),
            ("Mixins Pattern", "Explain the concept and implementation of Mixin classes in Python object-oriented design.", "Medium", "Conceptual", "A mixin is a lightweight class designed to provide specific reusable methods to other classes via multiple inheritance, without being intended for standalone instantiation. Mixins typically do not maintain instance state and allow modular composition of behaviors across unrelated class hierarchies."),
            ("Abstract Base Classes (ABCs)", "How do Abstract Base Classes (ABCs) in Python enforce interface compliance at instantiation time?", "Medium", "Technical", "Using the abc module and @abstractmethod decorator, an ABC marks methods that must be overridden by concrete subclasses. If a subclass fails to implement any abstract method, Python raises a TypeError at instantiation time, ensuring strict interface compliance before runtime execution."),
            ("__new__ vs __init__", "What is the operational difference between __new__ and __init__ during Python object creation?", "Hard", "Technical", "__new__ is a static method responsible for creating and returning a new instance of the class (allocating memory). __init__ is an instance method responsible for initializing the newly created instance. Overriding __new__ is necessary when subclassing immutable types (like tuple, str, int) or implementing singletons."),
            ("Dataclasses vs Namedtuples", "Compare Python dataclasses with namedtuples regarding mutability, performance, and features.", "Medium", "Technical", "namedtuples are lightweight, immutable tuple subclasses with named fields, offering minimal memory overhead and unpackability, but lacking default methods or mutable state. dataclasses (PEP 557) are standard Python classes with auto-generated dunder methods (__init__, __repr__, __eq__), supporting mutable fields, inheritance, and post-init processing."),
            ("Metaclasses vs __init_subclass__", "What are metaclasses in Python, and how does __init_subclass__ offer a simpler alternative for class customization?", "Hard", "Technical", "A metaclass is the class of a class, defining how classes themselves are constructed (type is the default metaclass). In Python 3.6+, __init_subclass__ allows a base class to intercept, validate, and customize the creation of its subclasses without requiring the complexity of a custom metaclass."),
            ("Operator Overloading", "How does Python implement operator overloading through special dunder methods?", "Easy", "Technical", "Python maps operators to special double-underscore methods on objects. For example, '+' invokes __add__, '==' invokes __eq__, and '<' invokes __lt__. When the left operand does not support the operation with the right operand, Python attempts the reflected dunder method (such as __radd__) on the right operand."),
            ("Class vs Instance Attributes", "What are the common pitfalls associated with mutable class-level attributes in Python?", "Easy", "Conceptual", "Class attributes are shared across all instances of a class. If a class attribute is a mutable container (like a list or dict) and is modified via an instance (e.g. self.items.append(x)), the change is reflected across all instances of the class. To make attributes instance-specific, they must be assigned to self inside __init__."),
        ]),
        ("Data Structures", [
            ("List vs Tuple Internals", "Compare the internal CPython memory allocation strategies of lists and tuples.", "Medium", "Technical", "Tuples are immutable fixed-size arrays allocated with the exact memory required, allowing CPython to cache deallocated small tuples. Lists are dynamic arrays with over-allocation growth patterns (typically ~12.5% buffer headroom) to ensure amortized O(1) append operations, which introduces memory overhead compared to tuples."),
            ("Dictionary Hash Table", "How does Python 3.6+ implement compact dictionaries, and how does it preserve insertion order?", "Hard", "Technical", "Python 3.6+ split the dictionary hash table into a sparse array of indices pointing into a compact, contiguous array of entries containing hash, key, and value. Entries are appended in the order they are inserted, guaranteeing insertion order while reducing memory consumption by 20% to 25% compared to the classic hash table."),
            ("Set Implementation & Time Complexity", "How are Python sets implemented internally, and why do they offer O(1) average lookup time?", "Easy", "Technical", "Python sets are implemented as hash tables containing keys without values. When checking membership ('x in s'), Python hashes the item and computes an index in the table. If no collision occurs, lookup takes O(1) time. In the worst case (all elements collide), lookup degrades to O(N)."),
            ("collections.defaultdict", "How does collections.defaultdict work internally, and what happens when accessing a non-existent key?", "Easy", "Technical", "defaultdict subclasses dict and takes a callable default_factory in its constructor. When a non-existent key is accessed via __getitem__, it calls the default_factory to construct a default value, inserts the key-value pair into the dictionary, and returns the newly generated value."),
            ("collections.Counter", "Explain the primary features of collections.Counter and its most common operations.", "Easy", "Technical", "Counter is a dictionary subclass designed for counting hashable objects. Elements are stored as dictionary keys and their counts as values. It provides utility methods like most_common(n), arithmetic operations (addition, subtraction, intersection of counts), and defaults to 0 for missing keys without raising KeyError."),
            ("collections.deque", "Why is collections.deque significantly faster than a Python list for FIFO queue operations?", "Medium", "Technical", "A Python list is a contiguous dynamic array, so popping or inserting at index 0 requires shifting all N subsequent elements in memory, yielding O(N) complexity. deque is implemented as a doubly linked list of fixed-size blocks (typically 64 elements), providing O(1) appends and pops from both ends."),
            ("heapq Priority Queue", "How does the heapq module implement min-heaps in Python, and how do you achieve max-heap behavior?", "Medium", "Technical", "heapq implements binary min-heaps on top of standard Python lists where the smallest element is always at index 0 (heap[0]). To achieve max-heap behavior, elements can be multiplied by -1 before insertion (for numeric data) or wrapped in a custom class overriding the __lt__ comparison method."),
            ("bisect Module", "How does the bisect module perform binary search on sorted sequences in Python?", "Medium", "Technical", "The bisect module provides bisect_left and bisect_right to locate insertion points in sorted sequences in O(log N) time using binary search, and insort to insert elements while maintaining sort order in O(N) time (due to list shifting)."),
            ("Hash Collisions & DoS", "How does CPython protect its dictionaries against hash collision denial-of-service (DoS) attacks?", "Hard", "Technical", "CPython applies SipHash-2-4 with a randomized secret seed initialized at Python process startup. This prevents attackers from crafting specific keys that produce identical hash values, which would otherwise force dictionary lookups to degrade from O(1) to O(N) worst-case collision chains."),
            ("array Module", "When should you use the standard library array module instead of a Python list?", "Medium", "Technical", "The array module stores homogeneous primitive C data types (such as integers or floats) in contiguous memory buffers without wrapping each element in a Python object pointer. This provides massive memory savings and faster serialization when dealing with millions of numbers."),
            ("Weak References (weakref)", "What problem does the weakref module solve in Python memory management?", "Hard", "Technical", "The weakref module allows developers to create references to objects without increasing their reference count. This is crucial for building caches, observer patterns, and circular graph structures without preventing cyclic garbage collection from deallocating the referenced objects."),
            ("Frozenset vs Set", "Why can frozensets be used as dictionary keys while standard sets cannot?", "Easy", "Conceptual", "Dictionary keys must be hashable, which requires an object to have an immutable hash value throughout its lifecycle. Sets are mutable and do not implement __hash__, whereas frozensets are immutable, implement __hash__, and can safely be used as dictionary keys or set elements."),
        ]),
        ("Exception Handling", [
            ("Exception Hierarchy", "Explain the difference between BaseException and Exception in the Python exception hierarchy.", "Medium", "Technical", "BaseException is the root of all exceptions in Python. SystemExit, KeyboardInterrupt, and GeneratorExit inherit directly from BaseException so they are not accidentally caught by generic 'except Exception:' clauses, ensuring user interrupts and process exits behave as expected."),
            ("try-except-else-finally", "Describe the exact execution flow of a try-except-else-finally block in Python.", "Easy", "Technical", "The try block runs first. If an exception occurs, matching except blocks execute. If no exception occurs, the else block runs. The finally block always runs before leaving the construct, regardless of whether exceptions were raised, handled, or re-raised, making it ideal for resource cleanup."),
            ("Exception Chaining (from)", "How does exception chaining work using the 'raise ... from ...' syntax in Python 3?", "Medium", "Technical", "'raise NewException from OriginalException' explicitly chains exceptions, attaching the original exception to the __cause__ attribute of the new exception. This provides full traceability in tracebacks. Using 'from None' explicitly suppresses the context (__suppress_context__ = True)."),
            ("Custom Exceptions", "What is the best practice for defining custom domain exceptions in a Python package?", "Easy", "Conceptual", "Best practice is to define a base custom exception class that inherits from Exception (e.g. class AppError(Exception): pass), and then have all specific domain errors inherit from that base class. This allows library consumers to catch all package errors with a single handler."),
            ("Context Managers (__enter__, __exit__)", "How does the context manager protocol work using __enter__ and __exit__?", "Medium", "Technical", "When entering a 'with' statement, __enter__ is called and its return value is bound to the target variable. Upon exiting the block, __exit__(exc_type, exc_val, exc_tb) is called with exception details if an error occurred. If __exit__ returns True, the exception is suppressed; otherwise, it propagates."),
            ("contextlib.contextmanager", "How does the @contextlib.contextmanager decorator transform a generator into a context manager?", "Medium", "Technical", "The generator yields exactly once. Code before the yield runs in __enter__, the yielded value is bound to the 'as' target, and code after the yield runs in a finally block inside __exit__. If an exception occurs in the with-block, it is re-raised inside the generator at the yield point."),
            ("Suppressing Exceptions with contextlib", "How does contextlib.suppress work, and when is it preferable to a bare try-except pass?", "Easy", "Technical", "contextlib.suppress(*exceptions) is a context manager that catches and silently ignores the specified exception types. It is more concise and explicit than a try-except block with pass, clearly communicating the intentional suppression of expected non-critical errors (such as FileNotFoundError during file removal)."),
            ("Catching Multiple Exceptions", "What is the correct syntax for catching multiple distinct exception types in a single except clause?", "Easy", "Technical", "Multiple exceptions must be passed as a tuple inside parentheses: 'except (ValueError, TypeError, KeyError) as e:'. Passing them without parentheses (e.g. 'except ValueError, TypeError:') is invalid syntax in Python 3."),
            ("Exception Groups (Python 3.11+)", "What are ExceptionGroups introduced in Python 3.11, and how does the 'except*' syntax handle them?", "Hard", "Technical", "ExceptionGroup represents multiple concurrent errors (common in asyncio TaskGroups). The 'except*' syntax allows matching and handling subsets of exceptions within the group by type concurrently, unwrapping and re-raising unhandled exceptions automatically."),
            ("sys.exc_info()", "What information does sys.exc_info() provide during active exception handling?", "Medium", "Technical", "sys.exc_info() returns a 3-element tuple (type, value, traceback) representing the exception currently being handled in the active thread. If no exception is currently being handled, it returns (None, None, None)."),
            ("traceback Module", "How can the traceback module be utilized to capture and format stack traces as strings for logging?", "Medium", "Technical", "traceback.format_exc() returns the full traceback string of the current exception, while traceback.print_exc() prints it directly to sys.stderr. traceback.extract_tb() allows programmatic inspection of individual stack frames (filename, line number, function name)."),
            ("Assertions (assert)", "Why should the 'assert' statement never be used for security-critical validation or business logic in production Python code?", "Easy", "Conceptual", "The 'assert' statement is designed exclusively for debugging. When Python is executed with the -O (optimize) flag, all assert statements are stripped from bytecode compilation, meaning any validation or security checks performed via assert will be completely skipped."),
        ]),
        ("Decorators", [
            ("Basic Decorator Architecture", "How does a standard Python decorator work as a syntactic wrapper around a callable?", "Easy", "Conceptual", "A decorator is a callable that takes another callable as an argument and returns a replacement callable. The '@decorator' syntax above a function def is syntactic sugar for 'func = decorator(func)', evaluated at module import time."),
            ("Decorators with Arguments", "How do you construct a decorator that accepts its own configuration arguments?", "Medium", "Technical", "A decorator with arguments requires three nested function layers: an outer factory function that accepts the decorator arguments, an intermediate decorator function that accepts the target function, and an innermost wrapper function that intercepts the actual function call and arguments."),
            ("functools.wraps Internals", "What specific attributes does functools.wraps copy from the decorated function onto the wrapper?", "Medium", "Technical", "functools.wraps copies __module__, __name__, __qualname__, __doc__, and __annotations__ from the original function to the wrapper, and assigns the original function to the wrapper's __wrapped__ attribute to allow unwrapping."),
            ("Class Decorators for Classes", "How do class decorators work when applied to a class definition rather than a function?", "Medium", "Technical", "A class decorator takes a class object as its argument, inspects or modifies its attributes and methods (or wraps it in a proxy class), and returns the modified class or replacement object. Common examples include @dataclass and @functools.total_ordering."),
            ("Class as a Decorator", "How can a Python class be designed to act as a decorator by implementing __call__?", "Medium", "Technical", "A class can act as a decorator by accepting the target function in its __init__ method and implementing the __call__ method to intercept subsequent function calls. This is useful for decorators that maintain persistent state across invocations."),
            ("Chaining Decorators", "In what order are multiple chained decorators applied and executed in Python?", "Easy", "Conceptual", "Decorators are applied from the bottom up (closest to the function definition first) during function definition, and their resulting wrappers are executed from the top down (outermost first) when the function is called."),
            ("Decorating Methods with self", "What special considerations must be taken into account when writing decorators intended for both functions and class methods?", "Medium", "Technical", "When decorating an instance method, the first positional argument passed to the wrapper will be 'self' (the instance). The decorator wrapper must accept *args and **kwargs to forward 'self' transparently to the underlying method."),
            ("Stateful Decorators", "How can a decorator maintain state (such as invocation counts) across multiple function calls?", "Medium", "Technical", "State can be maintained either by attaching attributes directly to the wrapper function object (since functions are first-class objects) or by using a class-based decorator with instance variables stored on self."),
            ("Unwrapping Decorators", "How can you access the original undecorated function when it has been wrapped using functools.wraps?", "Medium", "Technical", "functools.wraps assigns the original function to the __wrapped__ attribute on the wrapper. You can access the original function directly via func.__wrapped__, or recursively unwrap multiple layers using inspect.unwrap(func)."),
            ("Type Preservation with ParamSpec", "How do typing.ParamSpec and typing.Concatenate enable fully type-safe decorators in modern Python?", "Hard", "Technical", "ParamSpec captures the exact parameter types and call signature of the decorated function, while Concatenate allows adding or removing parameters. This ensures that Mypy and IDEs preserve full autocomplete and argument validation on decorated functions."),
            ("Validation Decorators", "Design a decorator pattern that validates input types against function type annotations at runtime.", "Hard", "Technical", "The decorator inspects func.__annotations__, pairs runtime arguments from *args and **kwargs with parameter names using inspect.signature().bind(), and checks each argument using isinstance(). If a mismatch occurs, it raises a TypeError before calling the underlying function."),
            ("Singleton Pattern via Decorator", "How can the Singleton pattern be implemented cleanly in Python using a class decorator?", "Medium", "Technical", "A singleton decorator maintains a dictionary mapping classes to their existing instances. When the decorated class is instantiated, the decorator checks the dictionary: if an instance already exists, it returns it; otherwise, it creates, caches, and returns the new instance."),
        ]),
        ("Generators", [
            ("Generator Function vs Expression", "What is the difference between a generator function using 'yield' and a generator expression?", "Easy", "Conceptual", "A generator function is declared with 'def' and uses the 'yield' keyword to produce values lazily. A generator expression uses comprehension syntax enclosed in parentheses (e.g. (x*2 for x in data)) to create an anonymous generator object on the fly."),
            ("Iterator Protocol", "Explain the Python iterator protocol and the contract between __iter__ and __next__.", "Easy", "Technical", "An iterable is an object defining __iter__, which returns an iterator. An iterator defines __next__, which returns the next item in the sequence or raises StopIteration when exhausted. Iterators also define __iter__ returning self to allow direct use in for-loops."),
            ("Memory Efficiency of Generators", "Why do generators provide superior memory efficiency when processing large datasets?", "Easy", "Conceptual", "Unlike lists that load the entire dataset into memory simultaneously (O(N) memory), generators yield one item at a time on demand (O(1) memory), discarding previously processed items and enabling streaming of gigabyte-scale files without exhaustion."),
            ("yield from Syntax", "How does the 'yield from' expression work, and what advantages does it offer over nested for-loops?", "Medium", "Technical", "'yield from iterable' delegates generation directly to a sub-generator. In addition to eliminating boilerplate nested loops, it establishes a transparent bi-directional communication channel, forwarding values, exceptions, and return values between caller and sub-generator."),
            ("generator.send() Method", "Explain how the generator.send() method turns a generator into a coroutine.", "Hard", "Technical", "The send(value) method resumes the generator and sends a value into it, which becomes the evaluated result of the current yield expression. Before calling send with a non-None value, the generator must be primed by advancing it to the first yield using next() or send(None)."),
            ("generator.throw() and close()", "What are the roles of generator.throw() and generator.close() in generator lifecycle management?", "Medium", "Technical", "throw(typ, val, tb) raises an exception inside the generator at the current yield point, allowing the generator to handle it or clean up. close() raises a GeneratorExit inside the generator; if the generator does not terminate or raise, a RuntimeError is thrown."),
            ("itertools.islice", "Why should itertools.islice be used instead of standard slicing syntax on generators?", "Easy", "Technical", "Generators do not support indexing or standard slice syntax (gen[0:5]) because they do not store elements in memory. itertools.islice(gen, start, stop, step) lazily consumes and yields items from the generator without materializing the underlying sequence into a list."),
            ("itertools Combinatorics", "Compare itertools.product, permutations, and combinations in Python.", "Medium", "Conceptual", "product computes the Cartesian product of input iterables. permutations returns all possible r-length ordered arrangements of elements where order matters. combinations returns all r-length subsets of elements where order does not matter and elements are not repeated."),
            ("Infinite Iterators", "Explain the behavior and use cases of itertools.count, cycle, and repeat.", "Easy", "Technical", "count(start, step) produces an infinite sequence of evenly spaced numbers. cycle(iterable) repeatedly cycles through the elements of an iterable indefinitely. repeat(elem, n) yields an element repeatedly, either n times or infinitely if n is omitted."),
            ("Generator Exit & Resource Leaks", "What happens to open resources inside a generator if the consumer breaks out of a for-loop early?", "Hard", "Technical", "When a consumer breaks out of a loop, the generator object becomes unreferenced and is garbage collected. During collection, CPython invokes generator.close(), which raises GeneratorExit at the yield point. Any 'finally' blocks inside the generator execute to close files or connections."),
            ("itertools.tee Pitfall", "How does itertools.tee create independent iterators, and what is its primary memory pitfall?", "Hard", "Technical", "itertools.tee splits an iterable into N independent iterators by storing consumed items in an internal FIFO queue until all iterators have consumed them. If one iterator advances far ahead of the others, the queue retains all intermediate items in memory, leading to high memory usage."),
            ("Asynchronous Generators", "What is an asynchronous generator in Python, and how does it integrate with 'async for'?", "Medium", "Technical", "An asynchronous generator is a function defined with 'async def' that contains 'yield' statements. It implements __aiter__ and __anext__, allowing items to be produced asynchronously using 'async for item in async_gen():', where awaiting I/O occurs between yielded elements."),
        ]),
        ("Concurrency", [
            ("The Global Interpreter Lock (GIL)", "What is the CPython Global Interpreter Lock (GIL), and why does it prevent multi-threaded CPU speedup?", "Medium", "Technical", "The GIL is a mutual exclusion lock used by CPython to prevent multiple native OS threads from executing Python bytecode simultaneously, protecting CPython's non-thread-safe reference counting memory management. Consequently, CPU-bound tasks cannot achieve multi-core parallelism with threads."),
            ("Threading vs Multiprocessing", "When should you use the threading module versus the multiprocessing module in Python?", "Easy", "Conceptual", "The threading module is ideal for I/O-bound tasks (network requests, file operations) because the GIL is released during system calls, allowing concurrent I/O waits. The multiprocessing module is required for CPU-bound tasks (data crunching, image processing) because it spawns separate OS processes with independent GILs."),
            ("concurrent.futures", "Compare ThreadPoolExecutor and ProcessPoolExecutor from the concurrent.futures module.", "Medium", "Technical", "Both provide a high-level API for asynchronous execution using pool workers. ThreadPoolExecutor uses worker threads within the same process (low overhead, shared memory, bound by GIL). ProcessPoolExecutor spawns separate worker processes (higher overhead, IPC serialization via pickle, true multi-core CPU execution)."),
            ("Race Conditions & Locks", "How does a threading.Lock prevent race conditions on shared state in multi-threaded Python programs?", "Easy", "Technical", "A race condition occurs when multiple threads concurrently read and write shared data without synchronization, causing non-deterministic corruption. threading.Lock provides mutual exclusion: a thread must acquire the lock before accessing shared state and release it afterward, serializing access."),
            ("threading.RLock", "Why would you choose a threading.RLock (Reentrant Lock) over a standard threading.Lock?", "Medium", "Technical", "A standard Lock cannot be acquired multiple times by the same thread; attempting to do so causes a deadlock. An RLock tracks the owning thread and recursion depth, allowing the owner to acquire the lock repeatedly, which is necessary when nested or recursive methods synchronize on the same lock."),
            ("Thread-Safe Queues", "Why is queue.Queue preferred over standard lists for inter-thread communication?", "Easy", "Technical", "Python's queue.Queue module provides built-in thread safety with internal locking and condition variables for thread coordination. Standard lists are not thread-safe for compound operations (e.g. check-then-pop), which causes race conditions without manual synchronization."),
            ("Multiprocessing IPC", "How do multiprocessing.Queue and multiprocessing.Pipe enable inter-process communication?", "Medium", "Technical", "Because processes have isolated memory spaces, they cannot share in-memory objects directly. multiprocessing.Queue and Pipe serialize objects using pickle, transmit the serialized bytes across OS pipes or Unix domain sockets, and deserialize them in the receiving process."),
            ("Multiprocessing Pool Methods", "What is the difference between pool.map, pool.map_async, and pool.imap in multiprocessing.Pool?", "Medium", "Technical", "pool.map blocks until all tasks complete and returns a list. pool.map_async returns an AsyncResult immediately without blocking. pool.imap returns an iterator that yields results lazily as chunks complete, reducing memory overhead for massive inputs."),
            ("Daemon Threads", "What is a daemon thread in Python, and how does its lifecycle differ from non-daemon threads?", "Easy", "Technical", "A daemon thread runs in the background without preventing the Python process from exiting. When only daemon threads remain active, the Python interpreter exits immediately, abruptly terminating them without running their finally blocks or flushing buffers."),
            ("Process Forking vs Spawning", "Compare the 'fork' and 'spawn' start methods in the multiprocessing module.", "Hard", "Technical", "'fork' (default on older Unix) copies the parent process memory space instantly via copy-on-write, but can inherit broken locks and cause deadlocks in multi-threaded parents. 'spawn' (default on Windows/macOS) starts a fresh Python interpreter and imports the main module, ensuring clean state at the expense of higher startup latency."),
            ("threading.Event", "How does a threading.Event coordinate state and signaling between threads?", "Easy", "Technical", "threading.Event manages an internal boolean flag (initially False). Threads can call wait() to block until the flag becomes True. Another thread calls set() to set the flag and wake all waiting threads, or clear() to reset the flag."),
            ("Free-Threaded Python (PEP 703)", "What architectural changes are introduced by PEP 703 to make the GIL optional in Python 3.13+?", "Hard", "Technical", "PEP 703 makes the GIL optional by replacing global reference counting with mimalloc thread-local allocators and biased reference counting, protecting container mutations with fine-grained per-object locks, and enabling true multi-threaded CPU parallelism in CPython."),
        ]),
        ("AsyncIO", [
            ("Event Loop Architecture", "How does the asyncio event loop coordinate asynchronous task execution on a single OS thread?", "Medium", "Technical", "The asyncio event loop maintains queues of ready callbacks, scheduled timers, and active I/O file descriptors via OS multiplexers (like epoll, kqueue, or IOCP). It executes coroutines until they yield control via 'await', at which point the loop dispatches other ready tasks until the awaited I/O completes."),
            ("Coroutines, Tasks, and Futures", "What is the relationship between Coroutines, Tasks, and Futures in asyncio?", "Medium", "Technical", "A coroutine is a function defined with 'async def'. A Future represents the eventual result of an asynchronous operation with callback mechanisms. A Task is a concrete subclass of Future that wraps a coroutine, scheduling it for immediate execution on the event loop."),
            ("asyncio.gather vs asyncio.wait", "Compare asyncio.gather and asyncio.wait regarding error handling and return structures.", "Medium", "Technical", "asyncio.gather aggregates multiple awaitables, runs them concurrently, and returns results in the exact order passed, with an optional return_exceptions flag. asyncio.wait takes a set of Tasks and returns two sets (done, pending) based on conditions like FIRST_COMPLETED or ALL_COMPLETED."),
            ("Blocking Code in AsyncIO", "Why must blocking synchronous code never be run directly in an async function, and how should it be executed?", "Medium", "Technical", "Because asyncio runs on a single thread, any blocking call (e.g. time.sleep(), requests.get()) blocks the entire event loop, freezing all concurrent tasks. Blocking code must be offloaded to a thread pool using loop.run_in_executor() or asyncio.to_thread()."),
            ("asyncio.TaskGroup (Python 3.11+)", "How does asyncio.TaskGroup improve structured concurrency over asyncio.gather?", "Medium", "Technical", "TaskGroup provides an asynchronous context manager ('async with asyncio.TaskGroup() as tg:'). If any child task fails, the remaining active tasks in the group are automatically cancelled, and exceptions are bundled into an ExceptionGroup, eliminating orphaned background tasks."),
            ("Async Context Managers", "Explain the protocol for creating asynchronous context managers using __aenter__ and __aexit__.", "Easy", "Technical", "An asynchronous context manager implements __aenter__ and __aexit__, both declared with 'async def'. Used with 'async with', __aenter__ is awaited upon entry to acquire resources, and __aexit__ is awaited upon block exit to release resources."),
            ("Async Iterators", "How do __aiter__ and __anext__ operate in asynchronous iteration?", "Easy", "Technical", "An asynchronous iterable defines __aiter__ returning an async iterator. The async iterator defines __anext__, which returns an awaitable that yields the next value or raises StopAsyncIteration when exhausted, consumed via 'async for'."),
            ("asyncio.Queue", "How does asyncio.Queue facilitate producer-consumer workflows without thread locks?", "Easy", "Technical", "asyncio.Queue provides asynchronous FIFO queueing where get() and put() are coroutines that suspend the calling task when the queue is empty or full, respectively, coordinating producers and consumers cooperatively on the single event loop."),
            ("asyncio.shield", "What is the purpose of asyncio.shield, and what is its common cancellation pitfall?", "Hard", "Technical", "asyncio.shield(task) protects a task from being cancelled if the outer enclosing coroutine is cancelled. However, if the shielded task itself is explicitly cancelled, it will terminate, and unhandled exceptions within the shielded task will still raise if not awaited."),
            ("asyncio.sleep vs time.sleep", "Explain the critical difference between asyncio.sleep() and time.sleep().", "Easy", "Conceptual", "time.sleep() is a synchronous blocking OS call that halts the entire thread and freezes the event loop. asyncio.sleep() is a non-blocking coroutine that yields control back to the event loop, scheduling a wakeup timer while letting other tasks run."),
            ("Signal Handling in AsyncIO", "How do you implement graceful shutdown of an asyncio application on SIGINT or SIGTERM?", "Hard", "Technical", "Register signal handlers using loop.add_signal_handler(). In the handler, cancel all pending tasks via asyncio.all_tasks(), aggregate them with asyncio.gather(*tasks, return_exceptions=True), and finally call loop.stop() after tasks have completed their cleanup routines."),
            ("AsyncIO Transport and Protocols", "What is the low-level Transport and Protocol abstraction in asyncio network programming?", "Hard", "Technical", "A Transport represents a bidirectional network connection (TCP/UDP socket) responsible for byte buffering and raw I/O. A Protocol is a callback interface implemented by the developer (e.g. data_received, connection_lost) that defines how incoming data is parsed and handled."),
        ]),
        ("Testing", [
            ("Pytest Fixtures & Scope", "Explain pytest fixture scopes (function, class, module, package, session) and tear-down mechanics.", "Medium", "Technical", "Pytest fixture scopes determine how frequently a fixture is invoked: 'function' runs for each test, 'class' once per test class, 'module' once per file, and 'session' once per test run. Yield fixtures execute setup code before 'yield' and teardown code after 'yield'."),
            ("unittest.mock.Mock vs MagicMock", "What is the difference between unittest.mock.Mock and MagicMock?", "Easy", "Technical", "MagicMock is a subclass of Mock that comes pre-configured with default implementations for almost all Python magic (dunder) methods (e.g. __iter__, __len__, __enter__, __exit__, __getitem__), making it suitable for mocking complex objects and context managers."),
            ("Mocking with patch", "How does unittest.mock.patch work, and why must you 'patch where an object is looked up, not where it is defined'?", "Medium", "Technical", "patch temporarily replaces a target attribute with a Mock during test execution. It must be patched in the module where the code under test imports and references it, because if module A imports function F from module B, patching B.F will not affect the reference already imported into module A."),
            ("Pytest Parametrization", "How does @pytest.mark.parametrize eliminate redundant test code?", "Easy", "Technical", "The @pytest.mark.parametrize decorator allows a single test function to be executed repeatedly with different sets of input arguments and expected outputs, generating distinct, independently reportable test cases for each parameter tuple."),
            ("Testing Exceptions with pytest.raises", "How do you verify that an exception is raised with the correct message using pytest?", "Easy", "Technical", "Use the 'with pytest.raises(ExpectedException, match=r'regex_pattern'):' context manager. It asserts that the expected exception is raised inside the block and optionally verifies the exception message against the regex pattern."),
            ("Mocking Async Functions", "How do you properly mock an asynchronous function using AsyncMock in unittest.mock?", "Medium", "Technical", "AsyncMock (introduced in Python 3.8) is designed for coroutines. When called, it returns an awaitable coroutine that resolves to the mock's return_value, allowing tests to await the mock call directly without raising TypeError."),
            ("Test Coverage & Branch Coverage", "What is the difference between statement coverage and branch coverage in pytest-cov?", "Medium", "Conceptual", "Statement coverage measures the percentage of code lines executed during tests. Branch coverage measures whether every branch of each conditional structure (e.g. both True and False branches of an if statement) has been executed, catching missed edge cases."),
            ("Property-Based Testing (Hypothesis)", "What is property-based testing, and how does the Hypothesis library differ from traditional unit tests?", "Hard", "Technical", "Traditional unit tests verify specific, hardcoded inputs against expected outputs. Property-based testing (via Hypothesis) defines general invariants and properties that must hold true for all valid inputs, generating hundreds of randomized inputs to find edge cases and shrinking failures to minimal examples."),
            ("Monkeypatching in Pytest", "How does pytest's built-in monkeypatch fixture safely modify environment variables and system state?", "Easy", "Technical", "The monkeypatch fixture provides methods like setenv(), delenv(), setattr(), and setitem() to modify global state, automatically reverting all modifications at the conclusion of the test function to prevent test pollution."),
            ("Doctest Framework", "What is Python's doctest module, and how does it verify documentation examples?", "Easy", "Technical", "The doctest module searches docstrings for snippets formatted like interactive Python shell sessions (prefixed with '>>>'), executes those code snippets, and asserts that the actual output matches the documented output, ensuring documentation stays up to date."),
            ("Integration vs Unit Testing", "Distinguish unit testing from integration testing in the context of database and external API interactions.", "Medium", "Conceptual", "Unit tests isolate a single component (function or class) in memory by mocking external dependencies (databases, network APIs). Integration tests execute multiple integrated components together against real or containerized services (e.g. Postgres via testcontainers) to verify end-to-end interactions."),
            ("Pytest Plugins & Hooks", "How do pytest hooks (like pytest_runtest_setup or pytest_addoption) enable custom test runners?", "Hard", "Technical", "Pytest uses a hook-based plugin architecture powered by pluggy. Developers can implement standard hook specifications in conftest.py to add command-line options, intercept test execution phases, customize test collection, and generate custom test reports."),
        ]),
    ]),
]
