"""add transcript and question evaluations

Revision ID: 6c8bbafb7ae6
Revises: 8ff6c73f2fd5
Create Date: 2026-08-29 19:29:51.445175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8bbafb7ae6'
down_revision: Union[str, Sequence[str], None] = '8ff6c73f2fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'job_role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('interviews', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_constraint(op.f('interviews_user_id_fkey'), 'interviews', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('interviews_user_id_fkey'), 'interviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.alter_column('interviews', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('interviews', 'difficulty',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('interviews', 'job_role',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
