"""add interview transcript and question evaluations

Revision ID: 7c9322fc499e
Revises: 6c8bbafb7ae6
Create Date: 2026-08-29 19:31:08.144361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9322fc499e'
down_revision: Union[str, Sequence[str], None] = '6c8bbafb7ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
