"""add question level evaluations

Revision ID: 8ff6c73f2fd5
Revises: b87f7e72125f
Create Date: 2026-08-29 19:25:01.975388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff6c73f2fd5'
down_revision: Union[str, Sequence[str], None] = 'b87f7e72125f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('question_evaluations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'question_evaluations')
    # ### end Alembic commands ###
