"""add user profiles

Revision ID: feb1bdc6a322
Revises: 2af2aa13c964
Create Date: 2026-08-27 16:49:50.563957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb1bdc6a322'
down_revision: Union[str, Sequence[str], None] = '2af2aa13c964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('skills', sa.String(length=2000), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=1000), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
