import re
from typing import Any

# Archetypes for each topic to generate realistic, diverse, non-repetitive interview problems

TOPIC_PATTERNS = {
    "Arrays": [
        ("Prefix Sum Range Query", "Calculate the sum of elements between indices L and R efficiently using precomputed prefix sums.", "O(n)", "O(n)", ["Prefix Sum", "Range Query", "Arrays"]),
        ("Dutch National Flag Sort", "Partition an array containing three distinct elements (0s, 1s, 2s) in linear time using three pointers.", "O(n)", "O(1)", ["Two Pointers", "Sorting", "In-Place"]),
        ("Subarray Sum Equals K", "Find the total number of continuous subarrays whose sum equals a given target integer k.", "O(n)", "O(n)", ["Hash Map", "Prefix Sum", "Subarrays"]),
        ("Product of Array Except Self", "Return an array output such that output[i] is equal to the product of all the elements of nums except nums[i].", "O(n)", "O(1)", ["Prefix Product", "Suffix Product"]),
        ("Set Matrix Zeroes", "Given an m x n integer matrix, if an element is 0, set its entire row and column to 0 in-place.", "O(m*n)", "O(1)", ["Matrix", "In-Place"]),
        ("Spiral Matrix Traversal", "Given an m x n matrix, return all elements of the matrix in spiral order.", "O(m*n)", "O(1)", ["Matrix", "Simulation"]),
        ("Rotate Array by K Steps", "Rotate an array to the right by k steps in-place.", "O(n)", "O(1)", ["Reversal", "Arrays"]),
        ("Merge Sorted Array In-Place", "Merge two sorted integer arrays nums1 and nums2 into a single sorted array in-place.", "O(m+n)", "O(1)", ["Two Pointers", "Sorting"]),
        ("Find Missing Number", "Given an array nums containing n distinct numbers in the range [0, n], return the only number in the range that is missing.", "O(n)", "O(1)", ["Bit Manipulation", "Math"]),
        ("Majority Element Boyer-Moore", "Find the majority element that appears more than floor(n / 2) times using optimal space.", "O(n)", "O(1)", ["Boyer-Moore", "Counting"]),
        ("Next Permutation", "Rearrange numbers into the lexicographically next greater permutation of numbers.", "O(n)", "O(1)", ["Permutation", "Greedy"]),
        ("Trapping Rain Water Volume", "Compute how much water an elevation map can trap after raining.", "O(n)", "O(1)", ["Two Pointers", "Monotonic Stack"]),
        ("Pascal's Triangle Row Generator", "Generate the k-th indexed row of Pascal's Triangle in linear space.", "O(k)", "O(k)", ["Math", "Combinatorics"]),
        ("Continuous Subarray Maximum Product", "Find a contiguous non-empty subarray within an array that has the largest product.", "O(n)", "O(1)", ["Dynamic Programming", "Greedy"]),
        ("Find Peak Element in Array", "Find a peak element in an array where nums[i] is strictly greater than its neighbors.", "O(log n)", "O(1)", ["Binary Search", "Arrays"]),
        ("Monotonic Array Check", "Determine whether an array is monotone increasing or monotone decreasing.", "O(n)", "O(1)", ["Inspection", "Arrays"]),
        ("Longest Consecutive Elements Sequence", "Find the length of the longest consecutive elements sequence in an unsorted array.", "O(n)", "O(n)", ["Hash Set", "Union Find"]),
        ("Insert Interval into Disjoint Set", "Insert a new interval into a sorted list of non-overlapping intervals and merge if necessary.", "O(n)", "O(n)", ["Intervals", "Greedy"]),
        ("Summary Ranges Formatter", "Return the smallest sorted list of ranges that cover all the numbers in the array exactly.", "O(n)", "O(1)", ["Intervals", "Formatting"]),
        ("Array Nesting Cycle Length", "Find the longest cycle length formed by index jumps according to array values.", "O(n)", "O(1)", ["Cycle Detection", "In-Place"]),
        ("Maximum Chunks To Make Sorted", "Find the maximum number of chunks an array can be divided into such that sorting each chunk individually sorts the entire array.", "O(n)", "O(1)", ["Prefix Max", "Greedy"]),
        ("Third Maximum Distinct Number", "Return the third distinct maximum number in an integer array, or the maximum if it does not exist.", "O(n)", "O(1)", ["Counting", "Heap"]),
        ("Partition Array into Disjoint Intervals", "Partition array into two continuous subarrays left and right such that every element in left is <= every element in right.", "O(n)", "O(1)", ["Prefix Max", "Greedy"]),
        ("Wiggle Sort Parity Alternating", "Reorder array such that nums[0] <= nums[1] >= nums[2] <= nums[3]...", "O(n)", "O(1)", ["In-Place", "Sorting"]),
    ],
    "Strings": [
        ("Valid Anagram Strings", "Given two strings s and t, return true if t is an anagram of s, and false otherwise.", "O(n)", "O(1)", ["Frequency Map", "Sorting"]),
        ("Group Anagrams by Signature", "Group an array of strings into anagram clusters using character frequency signatures.", "O(n * k)", "O(n * k)", ["Hash Map", "String Canonicalization"]),
        ("Longest Common Prefix Search", "Find the longest common prefix string amongst an array of strings.", "O(n * m)", "O(1)", ["String Matching", "Trie"]),
        ("String to Integer Atoi Converter", "Implement the myAtoi function which converts a string to a 32-bit signed integer.", "O(n)", "O(1)", ["Parsing", "State Machine"]),
        ("Roman Numeral to Integer Parser", "Convert a valid standard Roman numeral string into its corresponding integer.", "O(n)", "O(1)", ["Hash Map", "Math"]),
        ("Integer to Roman Converter", "Convert an integer in range [1, 3999] into its Roman numeral representation.", "O(1)", "O(1)", ["Greedy", "Math"]),
        ("Zigzag String Conversion", "Format a string in a zigzag pattern across numRows rows and read row by row.", "O(n)", "O(n)", ["Simulation", "Matrix"]),
        ("Multiply Large Strings", "Given two non-negative integers num1 and num2 represented as strings, return their product as a string.", "O(n * m)", "O(n + m)", ["Math", "Simulation"]),
        ("Decode Encoded String", "Given an encoded string with k[encoded_string] format, return its decoded expansion.", "O(n)", "O(n)", ["Stack", "Recursion"]),
        ("Compare Version Numbers", "Compare two version strings version1 and version2 considering revision numbers.", "O(n + m)", "O(1)", ["Two Pointers", "Parsing"]),
        ("Isomorphic String Mapping", "Determine if two strings s and t are isomorphic under a bijection of characters.", "O(n)", "O(1)", ["Hash Map", "Bijective Mapping"]),
        ("Word Pattern Matching", "Given a pattern and a string s, find if s follows the same pattern bijection.", "O(n)", "O(k)", ["Hash Map", "Tokens"]),
        ("Repeated DNA Sequences", "Find all the 10-letter-long sequences that occur more than once in a DNA molecule.", "O(n)", "O(n)", ["Rabin-Karp", "Bitmask", "Hash Set"]),
        ("Restore Valid IP Addresses", "Generate all possible valid IP addresses that can be formed from a numeric string.", "O(1)", "O(1)", ["Backtracking", "Parsing"]),
        ("Longest Palindromic Chunk Decomposition", "Return the largest possible k such that string can be decomposed into k palindromic chunks.", "O(n)", "O(1)", ["Greedy", "Rolling Hash"]),
        ("Valid Palindrome Alphanumeric", "Verify if a string is a palindrome considering only alphanumeric characters and ignoring cases.", "O(n)", "O(1)", ["Two Pointers", "String Clean"]),
        ("Count and Say Sequence", "Generate the n-th term of the count-and-say run-length sequence.", "O(2^n)", "O(2^n)", ["Run-Length Encoding", "Recursion"]),
        ("Reorganize String No Adjacent Same", "Rearrange characters of a string so that any two adjacent characters are not the same.", "O(n log k)", "O(k)", ["Heap", "Greedy"]),
        ("Valid Parenthesis String with Wildcards", "Determine if a string with parentheses and asterisk wildcards '*' can be valid.", "O(n)", "O(1)", ["Greedy", "Range Tracking"]),
        ("Minimum Remove for Valid Parentheses", "Remove minimum number of parentheses so that the resulting parentheses string is valid.", "O(n)", "O(n)", ["Stack", "String Rebuild"]),
    ],
    "Hashing": [
        ("Two Sum Difference Target", "Find pairs in an array having an absolute difference equal to target k.", "O(n)", "O(n)", ["Hash Set", "Counting"]),
        ("Subarray Sum Divisible by K", "Find the number of non-empty continuous subarrays whose sum is divisible by k.", "O(n)", "O(k)", ["Prefix Sum", "Modular Arithmetic"]),
        ("First Unique Character Finder", "Find the first non-repeating character in a string and return its index.", "O(n)", "O(1)", ["Frequency Map", "Counting"]),
        ("Intersection of Multiple Arrays", "Given a 2D integer array nums, return a sorted list of distinct integers that appear in every array.", "O(n * m)", "O(k)", ["Frequency Map", "Set Intersection"]),
        ("Happy Number Detection", "Determine if a number is happy using cycle detection on sum of squared digits.", "O(log n)", "O(log n)", ["Hash Set", "Floyd Cycle"]),
        ("Contains Duplicate within Distance K", "Determine if there are two distinct indices i and j such that nums[i] == nums[j] and abs(i - j) <= k.", "O(n)", "O(k)", ["Sliding Window", "Hash Set"]),
        ("Bulls and Cows Secret Game", "Count exact match digits (bulls) and misplaced digit matches (cows).", "O(n)", "O(1)", ["Counting", "Hash Map"]),
        ("Find All Anagrams in String", "Find all start indices of t's anagrams in s using a sliding frequency signature.", "O(n)", "O(1)", ["Sliding Window", "Hash Map"]),
        ("Least Bricks Crossed in Wall", "Draw a vertical line from top to bottom of a brick wall that crosses the fewest bricks.", "O(total_bricks)", "O(distinct_edges)", ["Hash Map", "Prefix Edge"]),
        ("Continuous Subarray Sum Multiple", "Check if array has continuous subarray of size at least 2 whose sum is a multiple of k.", "O(n)", "O(min(n, k))", ["Prefix Sum", "Modular Hash"]),
        ("Contiguous Binary Array Equal 0 and 1", "Find the maximum length of a contiguous subarray with an equal number of 0 and 1.", "O(n)", "O(n)", ["Prefix Sum", "Hash Map"]),
        ("Group Shifted String Sequences", "Group strings that belong to the same shifting sequence under Caesar cipher.", "O(n * k)", "O(n * k)", ["Canonical Hash", "String"]),
        ("Custom String Sorting Order", "Sort the characters of string s so that they match the order that order was sorted.", "O(n + m)", "O(1)", ["Counting Sort", "Hash Map"]),
        ("Hand of Straights Consecutive Groups", "Rearrange cards into groups of size groupSize consisting of consecutive integers.", "O(n log n)", "O(n)", ["Ordered Map", "Greedy"]),
        ("Time-Based Key-Value Store", "Design a time-based key-value data structure that can store multiple values for the same key at different timestamps.", "O(log n)", "O(n)", ["Binary Search", "Hash Map"]),
    ],
    "Two Pointers": [
        ("Container with Most Water", "Find two vertical lines that together with the x-axis form a container holding the most water.", "O(n)", "O(1)", ["Greedy", "Two Pointers"]),
        ("Three Sum Zero Target", "Find all unique triplets in the array which gives the sum of zero.", "O(n^2)", "O(1)", ["Sorting", "Two Pointers"]),
        ("Four Sum Quadruplets", "Find all unique quadruplets [nums[a], nums[b], nums[c], nums[d]] which sum to target.", "O(n^3)", "O(1)", ["Sorting", "Two Pointers"]),
        ("Remove Duplicates Sorted Array", "Remove duplicates in-place from sorted array and return new length.", "O(n)", "O(1)", ["In-Place", "Two Pointers"]),
        ("Move Zeroes to End", "Move all 0's to the end of array while maintaining relative order of non-zero elements.", "O(n)", "O(1)", ["In-Place", "Two Pointers"]),
        ("Sort Colors In-Place", "Sort an array of 0s, 1s, and 2s in-place without using the library sort function.", "O(n)", "O(1)", ["Three Pointers", "Partition"]),
        ("Squares of Sorted Array", "Given an integer array nums sorted in non-decreasing order, return an array of the squares of each number sorted.", "O(n)", "O(n)", ["Two Pointers", "Sorting"]),
        ("Valid Palindrome After One Deletion", "Determine if a string can be a palindrome after deleting at most one character.", "O(n)", "O(1)", ["Greedy", "Two Pointers"]),
        ("Boats to Rescue People", "Find the minimum number of boats to carry every person within maximum weight limit.", "O(n log n)", "O(1)", ["Greedy", "Two Pointers"]),
        ("Three Sum Closest Sum", "Find three integers in nums such that the sum is closest to target.", "O(n^2)", "O(1)", ["Sorting", "Two Pointers"]),
        ("Minimum Size Subarray Sum", "Find the minimal length of a contiguous subarray of which the sum >= target.", "O(n)", "O(1)", ["Two Pointers", "Sliding Window"]),
        ("Longest Mountain Subarray", "Find the length of the longest subarray that forms a strict mountain peak.", "O(n)", "O(1)", ["Two Pointers", "Peak Detection"]),
    ],
    "Sliding Window": [
        ("Max Sum Subarray Size K", "Find the maximum sum of any contiguous subarray of size k.", "O(n)", "O(1)", ["Fixed Window", "Prefix Sum"]),
        ("Longest Substring K Distinct", "Find length of longest substring that contains at most k distinct characters.", "O(n)", "O(k)", ["Variable Window", "Hash Map"]),
        ("Fruit Into Baskets", "Find maximum number of fruits you can pick with at most two distinct types of trees.", "O(n)", "O(1)", ["Two Pointers", "Frequency Map"]),
        ("Minimum Window Substring", "Find minimum window substring in s that contains all characters of t.", "O(n)", "O(k)", ["Frequency Map", "Two Pointers"]),
        ("Permutation in String Window", "Check if s2 contains a permutation of s1 as a continuous substring.", "O(n)", "O(1)", ["Fixed Window", "Frequency Match"]),
        ("Sliding Window Maximum Deque", "Find maximum element in every sliding window of size k moving across array.", "O(n)", "O(k)", ["Monotonic Deque", "Sliding Window"]),
        ("Subarrays with K Different Integers", "Count continuous subarrays having exactly k different integers.", "O(n)", "O(k)", ["Sliding Window", "Exact K Difference"]),
        ("Max Consecutive Ones with K Flips", "Find maximum number of consecutive 1's in binary array if you can flip at most k 0's.", "O(n)", "O(1)", ["Two Pointers", "Zero Counter"]),
        ("Longest Repeating Character Replacement", "Find length of longest substring containing same letter after at most k replacements.", "O(n)", "O(1)", ["Frequency Window", "Greedy"]),
        ("Grumpy Bookstore Owner Satisfaction", "Maximize customer satisfaction by choosing a continuous window of size minutes to suppress grumpy state.", "O(n)", "O(1)", ["Fixed Window", "Prefix Diff"]),
    ],
    "Stack": [
        ("Valid Nested Parentheses", "Given a string containing just '(', ')', '{', '}', '[' and ']', determine if input string is valid.", "O(n)", "O(n)", ["Stack", "Matching"]),
        ("Min Stack with O(1) Minimum", "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.", "O(1)", "O(n)", ["Auxiliary Stack", "Design"]),
        ("Evaluate Reverse Polish Notation", "Evaluate the value of an arithmetic expression in Reverse Polish Notation (Postfix).", "O(n)", "O(n)", ["Stack", "Math"]),
        ("Daily Temperatures Wait Time", "Given array of daily temperatures, return array of days to wait for a warmer temperature.", "O(n)", "O(n)", ["Monotonic Stack", "Arrays"]),
        ("Next Greater Element in Array", "Find the next greater element for each item in an array using a monotonic stack.", "O(n)", "O(n)", ["Monotonic Stack", "Hash Map"]),
        ("Largest Rectangle in Histogram", "Find the area of the largest rectangle in the histogram of bar heights.", "O(n)", "O(n)", ["Monotonic Stack", "Geometry"]),
        ("Maximal Rectangle in Binary Matrix", "Given a rows x cols binary matrix filled with 0's and 1's, find the largest rectangle containing only 1's.", "O(m*n)", "O(n)", ["Histogram Stack", "DP"]),
        ("Online Stock Span Tracker", "Calculate the span of a stock's price today, defined as max consecutive days price <= today.", "O(1) amortized", "O(n)", ["Monotonic Stack", "Design"]),
        ("Remove K Digits for Smallest Number", "Remove k digits from number string so that new number is the smallest possible.", "O(n)", "O(n)", ["Greedy", "Monotonic Stack"]),
        ("132 Pattern Subsequence Detection", "Find if there exists a 132 pattern: three indices i < j < k such that nums[i] < nums[k] < nums[j].", "O(n)", "O(n)", ["Monotonic Stack", "Subsequence"]),
        ("Asteroid Collision Simulator", "Simulate collision of asteroids moving along a line with different speeds and directions.", "O(n)", "O(n)", ["Stack", "Simulation"]),
        ("Validate Stack Sequences", "Given pushed and popped sequences with distinct values, return true if this could have been valid.", "O(n)", "O(n)", ["Stack", "Greedy"]),
    ],
    "Queue / Deque": [
        ("Implement Queue using Dual Stacks", "Implement a first-in first-out (FIFO) queue using only two stacks.", "O(1) amortized", "O(n)", ["Stack", "Queue Design"]),
        ("Design Circular Ring Queue", "Design your implementation of the circular queue with fixed capacity.", "O(1)", "O(k)", ["Ring Buffer", "Array"]),
        ("Moving Average from Data Stream", "Calculate moving average of all integers in the sliding window of size size.", "O(1)", "O(k)", ["Queue", "Sliding Window"]),
        ("Dota2 Senate Radiant vs Dire", "Simulate Senate voting procedure where senators can ban next opposing senator.", "O(n)", "O(n)", ["Queue", "Greedy"]),
        ("Recent Calls Rate Limiter", "Count number of recent requests within a time frame of [t - 3000, t] milliseconds.", "O(1) amortized", "O(n)", ["Queue", "Time Window"]),
        ("Shortest Subarray with Sum at Least K", "Return length of shortest non-empty subarray with sum at least k.", "O(n)", "O(n)", ["Monotonic Deque", "Prefix Sum"]),
        ("Reveal Cards in Increasing Order", "Reorder deck so that when revealing first and moving next to bottom, cards appear sorted.", "O(n)", "O(n)", ["Deque", "Simulation"]),
    ],
    "Linked List": [
        ("Reverse Singly Linked List", "Reverse a singly linked list iteratively and return the new head.", "O(n)", "O(1)", ["Pointers", "Linked List"]),
        ("Merge Two Sorted Linked Lists", "Merge two sorted linked lists and return it as a sorted list.", "O(n+m)", "O(1)", ["Two Pointers", "Linked List"]),
        ("Reorder Linked List In-Place", "Reorder list L0 -> L1 -> ... -> Ln-1 -> Ln to L0 -> Ln -> L1 -> Ln-1 -> L2...", "O(n)", "O(1)", ["Fast Slow Pointers", "Reversal"]),
        ("Remove Nth Node From End of List", "Remove the nth node from the end of the list and return its head in one pass.", "O(n)", "O(1)", ["Fast Slow Pointers", "Two Pointers"]),
        ("Detect Cycle in Linked List", "Determine if a linked list has a cycle using Floyd's Tortoise and Hare algorithm.", "O(n)", "O(1)", ["Floyd Cycle", "Two Pointers"]),
        ("Linked List Cycle II Entry Point", "Return the node where the cycle begins in a linked list, or null if no cycle exists.", "O(n)", "O(1)", ["Floyd Cycle", "Pointers"]),
        ("Intersection Node of Two Lists", "Find the node at which the intersection of two singly linked lists begins.", "O(n+m)", "O(1)", ["Two Pointers", "Pointers Align"]),
        ("Add Two Numbers as Linked Lists", "Add two numbers represented by linked lists with digits in reverse order.", "O(max(n, m))", "O(max(n, m))", ["Math", "Simulation"]),
        ("Reverse Nodes in K-Group", "Reverse the nodes of a linked list k at a time and return its modified head.", "O(n)", "O(1)", ["Pointers", "Recursion"]),
        ("Partition List Around Value X", "Partition linked list such that all nodes less than x come before nodes greater or equal to x.", "O(n)", "O(1)", ["Two Pointers", "List Assembly"]),
        ("Sort Linked List with Merge Sort", "Sort a linked list in O(n log n) time and O(log n) stack space using merge sort.", "O(n log n)", "O(log n)", ["Merge Sort", "Divide and Conquer"]),
        ("Flatten Multilevel Doubly Linked List", "Flatten a multilevel doubly linked list where nodes may have a child list.", "O(n)", "O(n)", ["DFS", "Stack"]),
        ("Palindrome Linked List Check", "Determine if a singly linked list is a palindrome in O(n) time and O(1) space.", "O(n)", "O(1)", ["Fast Slow", "Reversal"]),
    ],
    "Binary Search": [
        ("Search in Rotated Sorted Array", "Search target in rotated sorted array with distinct values in O(log n) time.", "O(log n)", "O(1)", ["Binary Search", "Pivot Search"]),
        ("Find Minimum in Rotated Sorted Array", "Find minimum element in sorted rotated array of unique elements.", "O(log n)", "O(1)", ["Binary Search", "Boundary Condition"]),
        ("Search 2D Matrix Sorted Rows", "Search target integer in an m x n matrix where each row is sorted and first integer of each row > last of previous.", "O(log(m*n))", "O(1)", ["Binary Search", "Coordinate Mapping"]),
        ("First and Last Position of Element", "Find starting and ending position of a given target value in sorted array in O(log n).", "O(log n)", "O(1)", ["Binary Search", "Bound Finding"]),
        ("Square Root Integer Binary Search", "Compute and return the integer square root of non-negative integer x.", "O(log x)", "O(1)", ["Binary Search", "Math"]),
        ("Capacity to Ship Packages in D Days", "Find least weight capacity of ship that will result in all packages shipped within d days.", "O(n log(sum))", "O(1)", ["Binary Search on Answer", "Greedy"]),
        ("Koko Eating Bananas Minimum Speed", "Find minimum integer eating speed k such that Koko eats all bananas within h hours.", "O(n log(max))", "O(1)", ["Binary Search on Answer", "Greedy"]),
        ("Split Array Largest Sum Minimization", "Split array into m non-empty subarrays such that the largest sum among them is minimized.", "O(n log(sum))", "O(1)", ["Binary Search on Answer", "Greedy"]),
        ("Median of Two Sorted Arrays", "Find the median of two sorted arrays of sizes m and n in O(log(min(m, n))) time.", "O(log(min(m, n)))", "O(1)", ["Binary Search Partition", "Divide and Conquer"]),
        ("Single Element in Sorted Duplicates", "Find single element in sorted array where every other element appears exactly twice.", "O(log n)", "O(1)", ["Binary Search", "Parity Index"]),
    ],
    "Trees": [
        ("Invert Binary Tree Mirror", "Invert a binary tree and return its root.", "O(n)", "O(h)", ["Recursion", "Tree Traversal"]),
        ("Maximum Depth of Binary Tree", "Find the maximum depth of a binary tree.", "O(n)", "O(h)", ["DFS", "Recursion"]),
        ("Same Tree Identity Check", "Given the roots of two binary trees p and q, check if they are structurally identical with same values.", "O(n)", "O(h)", ["DFS", "Recursion"]),
        ("Subtree of Another Tree Check", "Check whether a binary tree tree2 is a subtree of tree1.", "O(n * m)", "O(h)", ["Tree Traversal", "Hashing"]),
        ("Lowest Common Ancestor Binary Tree", "Find lowest common ancestor of two nodes in a general binary tree.", "O(n)", "O(h)", ["DFS", "Recursion"]),
        ("Binary Tree Level Order Traversal", "Return the level order traversal of its nodes' values (i.e., from left to right, level by level).", "O(n)", "O(n)", ["BFS", "Queue"]),
        ("Binary Tree Right Side View", "Return values of nodes visible from right side of tree ordered top to bottom.", "O(n)", "O(h)", ["BFS", "DFS"]),
        ("Count Good Nodes in Binary Tree", "Count nodes X where in path from root to X there are no nodes with value greater than X.", "O(n)", "O(h)", ["DFS", "Path Max"]),
        ("Construct Tree from Preorder Inorder", "Construct binary tree given preorder and inorder traversal arrays.", "O(n)", "O(n)", ["Divide and Conquer", "Hash Map"]),
        ("Binary Tree Maximum Path Sum", "Find maximum path sum where path can start and end at any node.", "O(n)", "O(h)", ["DFS", "Post-Order"]),
        ("Serialize Deserialize Binary Tree", "Design an algorithm to serialize and deserialize a binary tree to/from a string.", "O(n)", "O(n)", ["BFS", "DFS", "String Encoding"]),
        ("Diameter of Binary Tree", "Compute the length of the longest path between any two nodes in a tree.", "O(n)", "O(h)", ["DFS", "Height Calculation"]),
        ("Balanced Binary Tree Verification", "Determine if a binary tree is height-balanced (depth of two subtrees never differs > 1).", "O(n)", "O(h)", ["DFS", "Height"]),
        ("Binary Tree Path Sum Equals Target", "Determine if tree has a root-to-leaf path such that adding all values equals targetSum.", "O(n)", "O(h)", ["DFS", "Backtracking"]),
        ("Symmetric Binary Tree Check", "Check whether a binary tree is a mirror of itself (symmetric around center).", "O(n)", "O(h)", ["DFS", "Queue"]),
        ("Flatten Binary Tree to Linked List", "Flatten binary tree into a linked list in-place using preorder traversal order.", "O(n)", "O(h)", ["Morris Traversal", "Recursion"]),
    ],
    "BST": [
        ("Validate Binary Search Tree Invariant", "Determine if a given binary tree is a valid Binary Search Tree.", "O(n)", "O(h)", ["Inorder Traversal", "Range Bounds"]),
        ("Kth Smallest Element in BST", "Find the kth smallest element in a binary search tree in O(h + k) time.", "O(h + k)", "O(h)", ["Inorder Traversal", "Stack"]),
        ("Lowest Common Ancestor in BST", "Find the lowest common ancestor node of two given nodes in a BST.", "O(h)", "O(1)", ["BST Property", "Pointers"]),
        ("Insert into Binary Search Tree", "Insert a new value into a binary search tree while maintaining BST property.", "O(h)", "O(h)", ["BST Traversal", "Recursion"]),
        ("Delete Node from BST Structure", "Delete a node with a given key from a BST and return new root.", "O(h)", "O(h)", ["Inorder Successor", "Recursion"]),
        ("Inorder Successor in BST Search", "Find the inorder successor of a node in a BST without parent pointers.", "O(h)", "O(1)", ["BST Property", "Search"]),
        ("Convert Sorted Array to Minimal BST", "Convert a sorted integer array into a height-balanced binary search tree.", "O(n)", "O(log n)", ["Divide and Conquer", "Recursion"]),
        ("Range Sum of BST Nodes", "Return the sum of values of all nodes with a value in the inclusive range [low, high].", "O(n)", "O(h)", ["Pruning", "DFS"]),
        ("Two Sum in BST Structure", "Find if there exist two elements in BST such that their sum equals a given target.", "O(n)", "O(h)", ["BST Iterator", "Two Pointers"]),
        ("Recover BST Swapped Nodes", "Recover a BST where exactly two nodes were swapped inadvertently without changing structure.", "O(n)", "O(1)", ["Morris Inorder", "Pointers"]),
    ],
    "Heap / Priority Queue": [
        ("Kth Largest Element in Unsorted Array", "Find the kth largest element in an unsorted array using a min-heap.", "O(n log k)", "O(k)", ["Min-Heap", "Quickselect"]),
        ("Top K Frequent Elements in Array", "Return the k most frequent elements given an integer array nums.", "O(n log k)", "O(n)", ["Bucket Sort", "Min-Heap"]),
        ("Find Median from Running Data Stream", "Design a data structure that calculates median of a stream of integers dynamically.", "O(log n)", "O(n)", ["Dual Heaps", "Design"]),
        ("Merge K Sorted Lists via Priority Queue", "Merge k sorted linked lists and return it as one sorted list.", "O(n log k)", "O(k)", ["Min-Heap", "Divide and Conquer"]),
        ("Task Scheduler Idle Slots Minimization", "Calculate least number of units of times that the CPU will take to finish all tasks.", "O(n)", "O(1)", ["Greedy", "Heap"]),
        ("K Closest Points to Origin", "Find the k closest points to origin (0, 0) in Euclidean plane.", "O(n log k)", "O(k)", ["Max-Heap", "Geometry"]),
        ("Reorganize String Distance Separation", "Rearrange characters so adjacent characters are not equal using max heap.", "O(n log k)", "O(k)", ["Max-Heap", "Greedy"]),
        ("Smallest Range Covering Elements from K Lists", "Find the smallest range that includes at least one number from each of the k lists.", "O(n log k)", "O(k)", ["Min-Heap", "Sliding Window"]),
        ("Minimum Cost to Connect Sticks", "Connect all sticks with minimum total cost where connecting two sticks costs x + y.", "O(n log n)", "O(n)", ["Min-Heap", "Greedy Huffman"]),
        ("Furthest Building Reached Bricks Ladders", "Find furthest building you can reach using given bricks and ladders optimally.", "O(n log k)", "O(k)", ["Min-Heap", "Greedy"]),
    ],
    "Graphs": [
        ("Number of Islands Grid Traversal", "Given an m x n 2D binary grid, count the number of connected components of '1's.", "O(m*n)", "O(m*n)", ["BFS", "DFS", "Flood Fill"]),
        ("Clone Undirected Graph Deep Copy", "Return a deep copy (clone) of a connected undirected graph.", "O(V + E)", "O(V)", ["BFS", "DFS", "Hash Map"]),
        ("Max Area of Island in Grid", "Find the maximum area of an island in a given binary matrix.", "O(m*n)", "O(m*n)", ["DFS", "Matrix"]),
        ("Pacific Atlantic Water Flow Bounds", "Find grid coordinates that can flow water to both Pacific and Atlantic oceans.", "O(m*n)", "O(m*n)", ["Multi-Source BFS", "DFS"]),
        ("Surrounded Regions Flip to X", "Capture surrounded regions by flipping all 'O's into 'X's that are not connected to border.", "O(m*n)", "O(m*n)", ["Border BFS", "Flood Fill"]),
        ("Rotting Oranges Grid Spread", "Determine minimum number of minutes that must elapse until no cell has a fresh orange.", "O(m*n)", "O(m*n)", ["Multi-Source BFS", "Simulation"]),
        ("Course Schedule Cycle Detection", "Determine if you can finish all courses given prerequisite graph using topological sort.", "O(V + E)", "O(V + E)", ["Kahn Algorithm", "DFS Cycle"]),
        ("Course Schedule II Ordering", "Return ordering of courses you should take to finish all courses using topological sort.", "O(V + E)", "O(V + E)", ["Topological Sort", "DAG"]),
        ("Graph Valid Tree Verification", "Determine if an undirected graph forms a valid tree (connected and acyclic).", "O(V + E)", "O(V)", ["Union Find", "BFS"]),
        ("Connected Components Count in Graph", "Find number of connected components in an undirected graph.", "O(V + E)", "O(V)", ["Union Find", "DFS"]),
        ("Redundant Connection Cycle Finder", "Find an edge that can be removed so that resulting graph is a tree of n nodes.", "O(n)", "O(n)", ["Union Find", "Disjoint Set"]),
        ("Word Ladder Shortest Transformation", "Find length of shortest transformation sequence from beginWord to endWord.", "O(m^2 * n)", "O(m * n)", ["Bidirectional BFS", "Shortest Path"]),
        ("Network Delay Time Dijkstra", "Send signal from node k to all n nodes with minimum time using Dijkstra algorithm.", "O(E log V)", "O(V + E)", ["Dijkstra", "Min-Heap"]),
        ("Cheapest Flights Within K Stops", "Find cheapest price from src to dst with at most k stops using Bellman-Ford or Dijkstra.", "O(K * E)", "O(V)", ["Bellman-Ford", "BFS"]),
        ("Is Graph Bipartite 2-Coloring", "Determine if an undirected graph is bipartite using 2-coloring BFS/DFS.", "O(V + E)", "O(V)", ["Graph Coloring", "BFS"]),
        ("Shortest Path in Binary Matrix", "Find length of shortest clear path in binary matrix from top-left to bottom-right.", "O(n^2)", "O(n^2)", ["BFS", "8-Directional"]),
        ("All Paths From Source to Target", "Find all possible paths from node 0 to node n-1 in DAG.", "O(2^V * V)", "O(V)", ["Backtracking", "DFS"]),
        ("Critical Connections Bridge Finder", "Find all critical connections (bridges) in a network using Tarjan's algorithm.", "O(V + E)", "O(V + E)", ["Tarjan Algorithm", "Bridges"]),
    ],
    "Greedy": [
        ("Jump Game Reachability Check", "Determine if you can reach the last index starting at index 0.", "O(n)", "O(1)", ["Greedy", "Max Reach"]),
        ("Jump Game II Minimum Steps", "Return minimum number of jumps to reach the last index.", "O(n)", "O(1)", ["Greedy", "BFS"]),
        ("Gas Station Complete Circuit", "Find starting gas station index that allows traveling around circuit once clockwise.", "O(n)", "O(1)", ["Greedy", "Prefix Sum"]),
        ("Non-overlapping Intervals Count", "Find minimum number of intervals to remove to make the rest of intervals non-overlapping.", "O(n log n)", "O(1)", ["Greedy", "Interval Scheduling"]),
        ("Minimum Arrows to Burst Balloons", "Find minimum number of arrows that must be shot to burst all balloons.", "O(n log n)", "O(1)", ["Intervals", "Greedy"]),
        ("Partition Labels Continuous Occurrence", "Partition string into as many parts as possible so each letter appears in at most one part.", "O(n)", "O(1)", ["Last Occurrence", "Greedy"]),
        ("Candy Distribution Rating Rule", "Find minimum number of candies to give children according to neighbor rating rule.", "O(n)", "O(n)", ["Two-Pass", "Greedy"]),
        ("Lemonade Change Register Simulation", "Determine if you can provide every customer with correct change in a lemonade stand.", "O(n)", "O(1)", ["Simulation", "Greedy"]),
        ("Boats to Save People Optimized", "Find minimum number of rescue boats carrying at most 2 people under weight limit.", "O(n log n)", "O(1)", ["Two Pointers", "Greedy"]),
        ("Car Pooling Capacity Check", "Determine if car with fixed capacity can pick up and drop off all passengers on schedule.", "O(n + 1000)", "O(1000)", ["Difference Array", "Greedy"]),
    ],
    "Dynamic Programming": [
        ("Climbing Stairs Distinct Ways", "Count distinct ways to reach top of staircase taking 1 or 2 steps each time.", "O(n)", "O(1)", ["Fibonacci", "DP"]),
        ("Min Cost Climbing Stairs", "Find minimum cost to reach top of floor paying cost at each step.", "O(n)", "O(1)", ["1D DP", "Space Optimized"]),
        ("House Robber Maximum Loot", "Determine maximum money you can rob tonight without alerting adjacent homes.", "O(n)", "O(1)", ["1D DP", "State Machine"]),
        ("House Robber II Circular Houses", "Determine maximum loot from circular arrangement of houses.", "O(n)", "O(1)", ["Circular DP", "Reduction"]),
        ("Longest Palindromic Substring DP", "Find longest palindromic substring in s using dynamic programming or expand around centers.", "O(n^2)", "O(1)", ["2D DP", "Centers"]),
        ("Palindromic Substrings Count", "Count how many palindromic substrings exist in a given string.", "O(n^2)", "O(1)", ["Centers", "DP"]),
        ("Decode Ways Message Count", "Decode numeric message where 'A' -> 1 ... 'Z' -> 26 and count total valid decodings.", "O(n)", "O(1)", ["Fibonacci DP", "String"]),
        ("Coin Change Minimum Coins", "Find fewest number of coins that you need to make up given amount from coin denominations.", "O(n * amount)", "O(amount)", ["Unbounded Knapsack", "1D DP"]),
        ("Coin Change II Total Ways", "Calculate number of distinct combinations that make up given amount of money.", "O(n * amount)", "O(amount)", ["Combinations", "1D DP"]),
        ("Word Break Dictionary Matching", "Determine if string s can be segmented into space-separated dictionary words.", "O(n^2 * k)", "O(n)", ["1D DP", "Trie"]),
        ("Longest Increasing Subsequence Length", "Find length of longest strictly increasing subsequence in integer array.", "O(n log n)", "O(n)", ["Patience Sort", "Binary Search DP"]),
        ("Partition Equal Subset Sum 0-1", "Determine if array can be partitioned into two subsets with equal sum.", "O(n * sum)", "O(sum)", ["0/1 Knapsack", "DP"]),
        ("Target Sum Ways Expression", "Find number of different expressions that evaluate to target using '+' and '-' signs.", "O(n * sum)", "O(sum)", ["Subset Sum", "DP"]),
        ("Edit Distance Levenshtein Measure", "Find minimum operations (insert, delete, replace) required to convert word1 to word2.", "O(n * m)", "O(min(n, m))", ["2D Grid DP", "String"]),
        ("Distinct Subsequences Count", "Count number of distinct subsequences of s which equals t.", "O(n * m)", "O(m)", ["2D DP", "String"]),
        ("Stock Trading Single Transaction", "Find maximum profit from buying and selling stock once.", "O(n)", "O(1)", ["Greedy", "Prefix Min"]),
        ("Stock Trading Multiple Transactions", "Find maximum profit from multiple buy/sell transactions.", "O(n)", "O(1)", ["Peak Valley", "Greedy"]),
        ("Maximal Square of Ones in Matrix", "Find largest square containing only 1's and return its area in binary matrix.", "O(m*n)", "O(n)", ["2D DP", "Geometry"]),
        ("Russian Doll Envelopes Nesting", "Find maximum number of envelopes you can Russian doll (put one inside another).", "O(n log n)", "O(n)", ["2D Sorting", "LIS DP"]),
        ("Longest Common Subsequence of Two Strings", "Find length of longest common subsequence between two strings.", "O(n * m)", "O(min(n, m))", ["2D DP", "String"]),
        ("Matrix Chain Multiplication Minimum Cost", "Find minimum scalar multiplications needed to multiply a chain of matrices.", "O(n^3)", "O(n^2)", ["Interval DP", "Matrix"]),
        ("Dungeon Game Health Management", "Determine knight's minimum initial health so that he can rescue princess at bottom-right.", "O(m*n)", "O(n)", ["Bottom-Up Grid DP", "State Constraints"]),
    ],
    "Backtracking": [
        ("Subsets Power Set Generator", "Given an integer array nums of unique elements, return all possible subsets (the power set).", "O(2^n)", "O(n)", ["Backtracking", "Combinatorics"]),
        ("Combination Sum Target Combination", "Find all unique combinations in candidates where candidate numbers sum to target.", "O(2^t)", "O(t)", ["Backtracking", "Unbounded Choice"]),
        ("Permutations All Orders", "Return all possible permutations of an array of distinct integers.", "O(n!)", "O(n)", ["Backtracking", "Swapping"]),
        ("Word Search in 2D Grid", "Given an m x n grid of characters and a word, return true if word exists in grid.", "O(m*n * 4^L)", "O(L)", ["Backtracking", "DFS"]),
        ("Letter Combinations of Phone Number", "Return all possible letter combinations that number could represent on telephone buttons.", "O(4^n)", "O(n)", ["Backtracking", "Cartesian Product"]),
        ("N-Queens Puzzle Solver", "Place n queens on an n x n chessboard such that no two queens attack each other.", "O(n!)", "O(n)", ["Diagonal Tracking", "Backtracking"]),
        ("Sudoku Grid Solver", "Write a program to solve a Sudoku puzzle by filling the empty cells.", "O(9^m)", "O(1)", ["Bitmask", "Backtracking"]),
        ("Generate Balanced Parentheses", "Generate all combinations of well-formed parentheses given n pairs.", "O(4^n / sqrt(n))", "O(n)", ["Catalan Numbers", "Backtracking"]),
        ("Palindrome Partitioning Strings", "Partition string s such that every substring of partition is a palindrome.", "O(n * 2^n)", "O(n)", ["Backtracking", "Palindrome Memo"]),
        ("Restore Valid IP Address Strings", "Generate all possible valid IP addresses from numeric string.", "O(1)", "O(1)", ["Backtracking", "IP Range"]),
    ],
    "Recursion": [
        ("Fast Power Exponentiation", "Implement pow(x, n), which calculates x raised to the power n (x^n) in O(log n).", "O(log n)", "O(log n)", ["Divide and Conquer", "Binary Exponentiation"]),
        ("Fibonacci Sequence Recursion", "Compute the n-th Fibonacci number using recursive memoization.", "O(n)", "O(n)", ["Recursion", "Memoization"]),
        ("Tower of Hanoi Move Simulator", "Simulate minimal moves for Tower of Hanoi puzzle with n disks.", "O(2^n)", "O(n)", ["Recursion", "Induction"]),
        ("K-th Symbol in Grammar Table", "Find the symbol at index k of row n generated by grammar rules.", "O(n)", "O(n)", ["Recursion", "Binary Tree"]),
        ("Integer Replacement Minimum Operations", "Find minimum number of operations to turn n to 1 by adding/subtracting 1 or dividing by 2.", "O(log n)", "O(log n)", ["Memoized Recursion", "Bitwise"]),
        ("Predict the Winner Minimax", "Determine if player 1 can win turn-based card game choosing ends of array.", "O(n^2)", "O(n)", ["Minimax", "Game Theory"]),
        ("Elimination Game Josephus Variant", "Find the last remaining number in a list of 1 to n after alternating left and right eliminations.", "O(log n)", "O(log n)", ["Recursion", "Math"]),
    ],
    "Bit Manipulation": [
        ("Single Number Odd Occurrence", "Find the single element in array where every other element appears twice.", "O(n)", "O(1)", ["XOR", "Bitwise"]),
        ("Number of 1 Bits Hamming Weight", "Count the number of set bits (1s) in an unsigned integer using Brian Kernighan algorithm.", "O(k)", "O(1)", ["Brian Kernighan", "Bitwise"]),
        ("Counting Bits Array Generator", "For every number i in range [0, n], count number of 1's in binary representation.", "O(n)", "O(n)", ["DP", "Bit Shift"]),
        ("Reverse Bits of 32-bit Integer", "Reverse bits of a given 32-bit unsigned integer.", "O(1)", "O(1)", ["Bit Shift", "Masking"]),
        ("Sum of Two Integers Without Plus", "Calculate sum of two integers a and b using bitwise operations without + or - operators.", "O(1)", "O(1)", ["Half Adder", "Bitwise"]),
        ("Bitwise AND of Numbers Range", "Given range [left, right], return bitwise AND of all numbers in this range inclusive.", "O(1)", "O(1)", ["Common Prefix", "Bit Shift"]),
        ("Minimum Bit Flips Convert Number", "Find minimum number of bit flips to convert integer start to goal.", "O(1)", "O(1)", ["XOR", "Hamming Distance"]),
        ("Power of Two Bitwise Check", "Determine if an integer is a power of two in constant time.", "O(1)", "O(1)", ["Bit Mask", "Math"]),
        ("Maximum XOR of Two Numbers in Array", "Find maximum result of nums[i] XOR nums[j] where 0 <= i <= j < n.", "O(n)", "O(1)", ["Bitwise Trie", "Greedy"]),
        ("Total Hamming Distance Pairs", "Calculate sum of Hamming distances between all pairs of given numbers.", "O(n)", "O(1)", ["Bit Column Count", "Combinatorics"]),
    ],
    "Trie": [
        ("Implement Trie Prefix Tree", "Implement insert, search, and startsWith methods of a Trie prefix tree.", "O(L)", "O(alphabet * L)", ["Trie", "Tree Design"]),
        ("Add and Search Words Data Structure", "Design a data structure that supports adding words and searching words with '.' wildcards.", "O(L)", "O(Total Chars)", ["Trie", "Backtracking"]),
        ("Word Search II Boggle Board", "Given an m x n board of characters and list of words, find all words on board using Trie.", "O(m*n * 4^L)", "O(Total Words)", ["Trie", "DFS Board"]),
        ("Replace Words with Prefix Root", "Replace all successors in sentence with shortest root prefix in dictionary.", "O(Sentence Length)", "O(Trie Size)", ["Trie", "Prefix Match"]),
        ("Map Sum Pairs Prefix Counter", "Design a map that supports sum of all values whose keys start with prefix.", "O(L)", "O(Total Chars)", ["Trie", "Prefix Sum"]),
        ("Maximum XOR Trie Query", "Find maximum XOR of a query value with any number in array using bitwise Trie.", "O(32)", "O(32 * n)", ["Bitwise Trie", "Greedy"]),
        ("Search Suggestions System", "Given array of products and searchWord, suggest at most 3 product names matching typed prefix.", "O(Total Chars)", "O(Trie)", ["Trie", "Autocomplete"]),
    ],
    "Segment Tree / Fenwick": [
        ("Range Sum Query Mutable Point Update", "Implement segment tree supporting point update and range sum queries in O(log n).", "O(log n)", "O(n)", ["Segment Tree", "Range Query"]),
        ("Range Minimum Query Segment Tree", "Build a segment tree supporting point update and range minimum query.", "O(log n)", "O(n)", ["Segment Tree", "RMQ"]),
        ("Fenwick Tree Binary Indexed Tree", "Implement Fenwick tree supporting prefix sum and point additions.", "O(log n)", "O(n)", ["Fenwick Tree", "Binary Indexed Tree"]),
        ("Count of Smaller Numbers After Self", "Count number of smaller elements to the right for each element using Fenwick tree.", "O(n log n)", "O(n)", ["Fenwick Tree", "Coordinate Compression"]),
        ("Count Inversions in Array", "Find total number of inversions (i < j and a[i] > a[j]) in array in O(n log n).", "O(n log n)", "O(n)", ["Fenwick Tree", "Merge Sort"]),
        ("Range Update Range Sum Lazy Propagation", "Implement segment tree with lazy propagation for range updates and range queries.", "O(log n)", "O(n)", ["Segment Tree", "Lazy Propagation"]),
    ],
    "Sorting": [
        ("Merge Sort Inversion Counter", "Sort an array and count number of inversions using recursive merge sort.", "O(n log n)", "O(n)", ["Divide and Conquer", "Merge Sort"]),
        ("Quick Sort In-Place Lomuto Partition", "Implement quicksort using Lomuto partitioning scheme.", "O(n log n)", "O(log n)", ["Partition", "Quick Sort"]),
        ("Heap Sort In-Place Array", "Sort an array using in-place heapify and extract-max routines.", "O(n log n)", "O(1)", ["Heapify", "Sorting"]),
        ("Counting Sort Non-Negative Array", "Sort array of small non-negative integers in linear time using frequency counts.", "O(n + k)", "O(k)", ["Non-Comparison Sort", "Linear Time"]),
        ("Radix Sort Multi-Digit Integers", "Sort integer array by processing individual digits using stable counting sort.", "O(d * (n + b))", "O(n + b)", ["Radix Sort", "Base Conversion"]),
        ("Largest Number Concatenation", "Given a list of non-negative integers, arrange them such that they form the largest number.", "O(n log n)", "O(n)", ["Custom Comparator", "Greedy"]),
        ("Sort Characters by Frequency Count", "Sort a string in decreasing order based on the frequency of the characters.", "O(n log k)", "O(k)", ["Bucket Sort", "Heap"]),
    ],
    "Math / Number Theory": [
        ("Greatest Common Divisor Euclidean", "Compute the greatest common divisor of two integers using the Euclidean algorithm.", "O(log(min(a, b)))", "O(1)", ["Euclidean Algorithm", "Math"]),
        ("Least Common Multiple Pair", "Compute least common multiple using LCM(a, b) = (a * b) / GCD(a, b).", "O(log(min(a, b)))", "O(1)", ["Number Theory", "Math"]),
        ("Sieve of Eratosthenes Prime Generation", "Count primes strictly less than n using the Sieve of Eratosthenes.", "O(n log log n)", "O(n)", ["Sieve", "Primes"]),
        ("Prime Factorization Decomposition", "Decompose an integer into its canonical prime factor representation.", "O(sqrt(n))", "O(log n)", ["Trial Division", "Number Theory"]),
        ("Extended Euclidean Linear Diophantine", "Find integers x and y such that a*x + b*y = gcd(a, b).", "O(log(min(a, b)))", "O(1)", ["Extended GCD", "Diophantine"]),
        ("Modular Multiplicative Inverse", "Find modular multiplicative inverse of a modulo m using Fermat's Little Theorem or Extended GCD.", "O(log m)", "O(1)", ["Modular Arithmetic", "Fermat"]),
        ("Count Trailing Zeroes in Factorial", "Given an integer n, return the number of trailing zeroes in n!.", "O(log n)", "O(1)", ["Legendre Formula", "Math"]),
        ("Ugly Numbers II Super Generator", "Find the n-th ugly number whose only prime factors are 2, 3, or 5.", "O(n)", "O(n)", ["Three Pointers", "DP"]),
        ("Fraction to Recurring Decimal String", "Convert numerator and denominator fraction into decimal string formatted with repeating parentheses.", "O(d)", "O(d)", ["Long Division", "Hash Map"]),
    ],
    "Advanced Algorithms": [
        ("KMP String Matching Algorithm", "Find all occurrences of pattern in text in linear time using Knuth-Morris-Pratt prefix function.", "O(n + m)", "O(m)", ["KMP", "Pi Table"]),
        ("Z-Algorithm Exact String Matching", "Compute the Z-array for string concatenation pattern$text for linear pattern matching.", "O(n + m)", "O(n + m)", ["Z-Array", "String Matching"]),
        ("Rabin-Karp Rolling Hash Matcher", "Find pattern in text using polynomial rolling hash with collision resolution.", "O(n + m)", "O(1)", ["Rolling Hash", "Modular Arithmetic"]),
        ("Tarjan Strongly Connected Components", "Find all strongly connected components in a directed graph using single DFS traversal.", "O(V + E)", "O(V)", ["Tarjan Algorithm", "DFS"]),
        ("Kosaraju Two-Pass SCC Finder", "Find all strongly connected components using graph transpose and reverse postorder DFS.", "O(V + E)", "O(V)", ["Kosaraju", "Topological"]),
        ("Hierholzer Eulerian Circuit Path", "Find an Eulerian circuit or path in directed/undirected graph.", "O(V + E)", "O(V + E)", ["Hierholzer", "Eulerian Path"]),
        ("Convex Hull Graham Scan Geometry", "Find the minimum convex polygon containing all points in a 2D plane.", "O(n log n)", "O(n)", ["Graham Scan", "Geometry"]),
        ("A-Star Shortest Path Heuristic", "Find shortest path on weighted grid using A* search with Euclidean or Manhattan heuristic.", "O(E)", "O(V)", ["A* Search", "Heuristic"]),
    ],
    "SQL": [
        ("Employee Second Highest Salary Query", "Write an SQL query to report the second highest salary from the Employee table.", "O(n)", "O(1)", ["SQL", "Aggregate", "LIMIT OFFSET"]),
        ("Customers Who Never Order Records", "Find all customers who never order anything using LEFT JOIN or NOT IN.", "O(n)", "O(1)", ["SQL", "LEFT JOIN", "NULL Check"]),
        ("Department Highest Salary Join", "Find employees who have the highest salary in each of the departments.", "O(n log n)", "O(1)", ["SQL", "Window Function", "RANK"]),
        ("Consecutive Numbers Logged Records", "Find all numbers that appear at least three times consecutively in Logs table.", "O(n)", "O(1)", ["SQL", "LEAD / LAG", "Self Join"]),
        ("Rising Temperature Weather Days", "Find all dates' Id with higher temperatures compared to its previous dates (yesterday).", "O(n)", "O(1)", ["SQL", "DATE_ADD", "Self Join"]),
        ("Exchange Seats Classroom Arrangement", "Swap the seat id of every two consecutive students in Seat table.", "O(n)", "O(1)", ["SQL", "CASE WHEN", "Window Function"]),
        ("Tree Node Hierarchy Classification", "Categorize each node in Tree table as 'Root', 'Leaf', or 'Inner'.", "O(n)", "O(1)", ["SQL", "CASE WHEN", "Subquery"]),
        ("Rank Scores Dense Rank Listing", "Rank the scores of games in descending order using DENSE_RANK without holes.", "O(n log n)", "O(1)", ["SQL", "DENSE_RANK", "Window"]),
        ("Department Top Three Unique Salaries", "Find the employees who earn top three unique salaries in each department.", "O(n log n)", "O(1)", ["SQL", "DENSE_RANK", "Partition"]),
        ("Human Traffic of Stadium Spikes", "Display the records with three or more consecutive rows with amount of people >= 100.", "O(n)", "O(1)", ["SQL", "Window Function", "Consecutive Rows"]),
    ],
    "Data Science / ML": [
        ("Confusion Matrix Precision Recall F1", "Calculate Precision, Recall, and F1-score given true binary labels and predictions.", "O(n)", "O(1)", ["Metrics", "Evaluation", "Classification"]),
        ("Mean Squared Error L2 Loss", "Calculate MSE loss with L2 regularization penalty for linear regression weights.", "O(n)", "O(1)", ["Loss Function", "Regularization", "Linear Regression"]),
        ("Sigmoid Activation and Gradient", "Compute output and gradient vector for Sigmoid activation function across inputs.", "O(n)", "O(1)", ["Activation Function", "Gradient", "Deep Learning"]),
        ("Softmax Normalization Vector", "Compute numerically stable Softmax probability vector subtracting max value.", "O(n)", "O(1)", ["Probability", "Softmax", "Numerical Stability"]),
        ("K-Means Nearest Centroid Assignment", "Assign each multi-dimensional sample vector to its nearest centroid Euclidean distance.", "O(n * k * d)", "O(1)", ["Clustering", "Euclidean Distance", "K-Means"]),
        ("Cosine Similarity Matrix Between Vectors", "Compute cosine similarity between two high-dimensional real vectors.", "O(d)", "O(1)", ["Vector Math", "Cosine Similarity", "NLP"]),
        ("TF-IDF Term Weight Calculation", "Calculate Term Frequency - Inverse Document Frequency score for a term in a document collection.", "O(N)", "O(1)", ["NLP", "TF-IDF", "Information Retrieval"]),
        ("Binary Cross-Entropy Loss Calculator", "Compute average binary cross-entropy loss between ground truth probabilities and predicted logits.", "O(n)", "O(1)", ["Loss Function", "Information Theory", "Log Loss"]),
    ]
}
